version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - makezero
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: false
    exhaustive:
      default-signifies-exhaustive: true
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - dupImport
        - octalLiteral
        - rangeValCopy
        - hugeParam
        - typeDefFirst
        - paramTypeCombine
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    godox:
      keywords:
        - BUG
        - FIXME
    govet:
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    lll:
      line-length: 140
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    revive:
      rules:
        - name: dot-imports
          arguments:
            - allowedPackages:
                - github.com/onsi/gomega
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gochecknoglobals
        source: ^var \S+ = regexp.MustCompile\(
      - linters:
          - errcheck
        path: main\.go
        source: ^\t+defer logger.Sync()
      - linters:
          - funlen
          - gocyclo
        path: main\.go
        source: ^func main()
      - linters:
          - gosec
        source: ^\t_ "net/http/pprof"
      - linters:
          - dupl
          - err113
          - errcheck
          - errorlint
          - funlen
          - gochecknoglobals
          - goconst
          - gocyclo
          - gosec
          - noctx
        path: _test\.go
      - linters:
          - gosec
        path: internal/hmac/
        text: weak cryptographic primitive
      - linters:
          - lll
        source: '^//go:generate '
      - linters:
          - err113
        source: ^.*fmt.Errorf.+
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
    - golines
  settings:
    goimports:
      local-prefixes:
        - github.com/selebrow/selebrow
    golines:
      max-len: 140
      tab-len: 4
      shorten-comments: false
      reformat-tags: true
      chain-split-dots: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
