filename: "{{.InterfaceName}}.go"
dir: "mocks"
structname: "{{ .InterfaceName }}"
pkgname: "mocks"
template: testify
packages:
    net:
      interfaces:
        Conn:
    net/http:
      interfaces:
        RoundTripper:
    hash:
      interfaces:
        Hash:
    golang.org/x/net/proxy:
      interfaces:
        ContextDialer:
    github.com/labstack/echo/v4:
      interfaces:
        Renderer:
    github.com/selebrow/selebrow:
      config:
        recursive: True
        all: True
