# Default values for selebrow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  # -- Repository image path without the tag
  repository: ghcr.io/selebrow/selebrow
  # -- Image pull policy (leave empty to apply default policy, see https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting)
  pullPolicy: ""
  # -- Overrides the image tag, whose default is the chart appVersion.
  tag: ""

# -- Image pull secrets
imagePullSecrets: []
# - name: registry-cred

# -- Overrides short application name
nameOverride: ""

# -- Overrides full application name used in service/deployment and other Kubernetes resources' names
fullnameOverride: ""

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Automatically mount a ServiceAccount's API credentials?
  automount: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and `create` is `true`, a name is generated using the fullname template
  name: ""

rbac:
  # -- Set to `true` to create role and role bindings for above service account
  create: true

# -- Additional Selebrow Pod annotations
podAnnotations: {}

# -- Additional Selebrow Pod labels
podLabels: {}

# -- Selebrow Pod [Security Context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/)
podSecurityContext: {}
  # fsGroup: 2000

# -- Selebrow container [Security Context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/)
securityContext:
  capabilities:
    drop:
     - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532

service:
  # -- Service [type](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types) to create
  type: ClusterIP
  # -- Service port
  port: 4444

ingress:
  # -- Enable ingress
  enabled: false
  # -- Ingress [class](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class)
  className: ""
  # -- Ingress [annotations](https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md)
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    # kubernetes.io/ingress.class: nginx
  # -- Ingress Host and request routing rules
  hosts:
    - host: selebrow.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  # -- TLS secrets by hosts
  tls: []
  # - secretName: chart-example-tls
  #   hosts:
  #     - chart-example.local

# -- Selebrow container [resource settings](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/)
resources: {}
  # limits:
  #   cpu: 500m
  #   memory: 512Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- Additional volumes for Selebrow Pod
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# -- Additional volumeMounts for Selebrow Pod
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

# -- Node selector for Selebrow Pod
nodeSelector: {}

# -- Tolerations for Selebrow Pod
tolerations: []

# -- Selebrow Pod affinity
affinity: {}

# -- Extra environment variables for Selebrow container
extraEnv: {}
# - name: SB_POOL_MAX_IDLE
#   value: "5"
# - name: SB_VNC_PASSWORD
#   valueFrom:
#     secretKeyRef:
#       name: selebrow
#       key: vnc-password


selebrow:
  # -- namespace to create browser Pods, leave empty to match Selebrow deployment namespace)
  # @section -- Selebrow service settings
  namespace: ""
  # -- Browsers catalog URI, leave empty to use fallback (remote) browsers URI
  # @section -- Selebrow service settings
  browserUri: ""
  quota:
    # -- Browsers quota limit, set to positive value to limit number of concurrently running browsers
    # @section -- Selebrow service settings
    limit: 0

templateValues:
  # -- Image pull secrets for the Pod
  # @section -- Browser template values
  imagePullSecrets: []
  # - name: registry-cred

  browser:
    # -- Additional environment variables for browser container
    # @section -- Browser template values
    env: {}
      # LANG: ru_RU.UTF-8
      # LANGUAGE: ru:en
      # TZ: Europe/Moscow

  # -- Pod annotations
  # @section -- Browser template values
  annotations: {}

  # -- Static Pod labels
  # @section -- Browser template values
  labels:
    app.kubernetes.io/created-by: selebrow

  # -- Search domains list
  # @section -- Browser template values
  searches: []

  # -- Custom Kubernetes scheduler to use (leave empty for default scheduler)
  # @section -- Browser template values
  scheduler: ""

  # -- Priority class to set on the Pod (leave empty for default priority)
  # @section -- Browser template values
  priorityClassName: ""

  # -- Image pull policy (leave empty to apply default policy, see https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting)
  # @section -- Browser template values
  imagePullPolicy: ""
