// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net/url"

	"github.com/selebrow/selebrow/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// NewBrowser creates a new instance of Browser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBrowser(t interface {
	mock.TestingT
	Cleanup(func())
}) *Browser {
	mock := &Browser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Browser is an autogenerated mock type for the Browser type
type Browser struct {
	mock.Mock
}

type Browser_Expecter struct {
	mock *mock.Mock
}

func (_m *Browser) EXPECT() *Browser_Expecter {
	return &Browser_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type Browser
func (_mock *Browser) Close(ctx context.Context, trash bool) {
	_mock.Called(ctx, trash)
	return
}

// Browser_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Browser_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
//   - trash bool
func (_e *Browser_Expecter) Close(ctx interface{}, trash interface{}) *Browser_Close_Call {
	return &Browser_Close_Call{Call: _e.mock.On("Close", ctx, trash)}
}

func (_c *Browser_Close_Call) Run(run func(ctx context.Context, trash bool)) *Browser_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Browser_Close_Call) Return() *Browser_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *Browser_Close_Call) RunAndReturn(run func(ctx context.Context, trash bool)) *Browser_Close_Call {
	_c.Run(run)
	return _c
}

// GetHost provides a mock function for the type Browser
func (_mock *Browser) GetHost() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHost")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Browser_GetHost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHost'
type Browser_GetHost_Call struct {
	*mock.Call
}

// GetHost is a helper method to define mock.On call
func (_e *Browser_Expecter) GetHost() *Browser_GetHost_Call {
	return &Browser_GetHost_Call{Call: _e.mock.On("GetHost")}
}

func (_c *Browser_GetHost_Call) Run(run func()) *Browser_GetHost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Browser_GetHost_Call) Return(s string) *Browser_GetHost_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Browser_GetHost_Call) RunAndReturn(run func() string) *Browser_GetHost_Call {
	_c.Call.Return(run)
	return _c
}

// GetHostPort provides a mock function for the type Browser
func (_mock *Browser) GetHostPort(name models.ContainerPort) string {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetHostPort")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(models.ContainerPort) string); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Browser_GetHostPort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHostPort'
type Browser_GetHostPort_Call struct {
	*mock.Call
}

// GetHostPort is a helper method to define mock.On call
//   - name models.ContainerPort
func (_e *Browser_Expecter) GetHostPort(name interface{}) *Browser_GetHostPort_Call {
	return &Browser_GetHostPort_Call{Call: _e.mock.On("GetHostPort", name)}
}

func (_c *Browser_GetHostPort_Call) Run(run func(name models.ContainerPort)) *Browser_GetHostPort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.ContainerPort
		if args[0] != nil {
			arg0 = args[0].(models.ContainerPort)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Browser_GetHostPort_Call) Return(s string) *Browser_GetHostPort_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Browser_GetHostPort_Call) RunAndReturn(run func(name models.ContainerPort) string) *Browser_GetHostPort_Call {
	_c.Call.Return(run)
	return _c
}

// GetURL provides a mock function for the type Browser
func (_mock *Browser) GetURL() *url.URL {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 *url.URL
	if returnFunc, ok := ret.Get(0).(func() *url.URL); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*url.URL)
		}
	}
	return r0
}

// Browser_GetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURL'
type Browser_GetURL_Call struct {
	*mock.Call
}

// GetURL is a helper method to define mock.On call
func (_e *Browser_Expecter) GetURL() *Browser_GetURL_Call {
	return &Browser_GetURL_Call{Call: _e.mock.On("GetURL")}
}

func (_c *Browser_GetURL_Call) Run(run func()) *Browser_GetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Browser_GetURL_Call) Return(uRL *url.URL) *Browser_GetURL_Call {
	_c.Call.Return(uRL)
	return _c
}

func (_c *Browser_GetURL_Call) RunAndReturn(run func() *url.URL) *Browser_GetURL_Call {
	_c.Call.Return(run)
	return _c
}
