// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/selebrow/selebrow/pkg/browser"
	"github.com/selebrow/selebrow/pkg/capabilities"
	"github.com/selebrow/selebrow/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// NewBrowserManager creates a new instance of BrowserManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBrowserManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *BrowserManager {
	mock := &BrowserManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BrowserManager is an autogenerated mock type for the BrowserManager type
type BrowserManager struct {
	mock.Mock
}

type BrowserManager_Expecter struct {
	mock *mock.Mock
}

func (_m *BrowserManager) EXPECT() *BrowserManager_Expecter {
	return &BrowserManager_Expecter{mock: &_m.Mock}
}

// Allocate provides a mock function for the type BrowserManager
func (_mock *BrowserManager) Allocate(ctx context.Context, protocol models.BrowserProtocol, caps capabilities.Capabilities) (browser.Browser, error) {
	ret := _mock.Called(ctx, protocol, caps)

	if len(ret) == 0 {
		panic("no return value specified for Allocate")
	}

	var r0 browser.Browser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.BrowserProtocol, capabilities.Capabilities) (browser.Browser, error)); ok {
		return returnFunc(ctx, protocol, caps)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.BrowserProtocol, capabilities.Capabilities) browser.Browser); ok {
		r0 = returnFunc(ctx, protocol, caps)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(browser.Browser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.BrowserProtocol, capabilities.Capabilities) error); ok {
		r1 = returnFunc(ctx, protocol, caps)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BrowserManager_Allocate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Allocate'
type BrowserManager_Allocate_Call struct {
	*mock.Call
}

// Allocate is a helper method to define mock.On call
//   - ctx context.Context
//   - protocol models.BrowserProtocol
//   - caps capabilities.Capabilities
func (_e *BrowserManager_Expecter) Allocate(ctx interface{}, protocol interface{}, caps interface{}) *BrowserManager_Allocate_Call {
	return &BrowserManager_Allocate_Call{Call: _e.mock.On("Allocate", ctx, protocol, caps)}
}

func (_c *BrowserManager_Allocate_Call) Run(run func(ctx context.Context, protocol models.BrowserProtocol, caps capabilities.Capabilities)) *BrowserManager_Allocate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.BrowserProtocol
		if args[1] != nil {
			arg1 = args[1].(models.BrowserProtocol)
		}
		var arg2 capabilities.Capabilities
		if args[2] != nil {
			arg2 = args[2].(capabilities.Capabilities)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *BrowserManager_Allocate_Call) Return(browser1 browser.Browser, err error) *BrowserManager_Allocate_Call {
	_c.Call.Return(browser1, err)
	return _c
}

func (_c *BrowserManager_Allocate_Call) RunAndReturn(run func(ctx context.Context, protocol models.BrowserProtocol, caps capabilities.Capabilities) (browser.Browser, error)) *BrowserManager_Allocate_Call {
	_c.Call.Return(run)
	return _c
}
