// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// BrowsersCatalogController is an autogenerated mock type for the BrowsersCatalogController type
type BrowsersCatalogController struct {
	mock.Mock
}

type BrowsersCatalogController_Expecter struct {
	mock *mock.Mock
}

func (_m *BrowsersCatalogController) EXPECT() *BrowsersCatalogController_Expecter {
	return &BrowsersCatalogController_Expecter{mock: &_m.Mock}
}

// Browsers provides a mock function with given fields: c
func (_m *BrowsersCatalogController) Browsers(c echo.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Browsers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BrowsersCatalogController_Browsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Browsers'
type BrowsersCatalogController_Browsers_Call struct {
	*mock.Call
}

// Browsers is a helper method to define mock.On call
//   - c echo.Context
func (_e *BrowsersCatalogController_Expecter) Browsers(c interface{}) *BrowsersCatalogController_Browsers_Call {
	return &BrowsersCatalogController_Browsers_Call{Call: _e.mock.On("Browsers", c)}
}

func (_c *BrowsersCatalogController_Browsers_Call) Run(run func(c echo.Context)) *BrowsersCatalogController_Browsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *BrowsersCatalogController_Browsers_Call) Return(_a0 error) *BrowsersCatalogController_Browsers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BrowsersCatalogController_Browsers_Call) RunAndReturn(run func(echo.Context) error) *BrowsersCatalogController_Browsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewBrowsersCatalogController creates a new instance of BrowsersCatalogController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBrowsersCatalogController(t interface {
	mock.TestingT
	Cleanup(func())
}) *BrowsersCatalogController {
	mock := &BrowsersCatalogController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
