// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/selebrow/selebrow/pkg/browser"
	"github.com/selebrow/selebrow/pkg/capabilities"
	"github.com/selebrow/selebrow/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// NewBrowserPool creates a new instance of BrowserPool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBrowserPool(t interface {
	mock.TestingT
	Cleanup(func())
}) *BrowserPool {
	mock := &BrowserPool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BrowserPool is an autogenerated mock type for the BrowserPool type
type BrowserPool struct {
	mock.Mock
}

type BrowserPool_Expecter struct {
	mock *mock.Mock
}

func (_m *BrowserPool) EXPECT() *BrowserPool_Expecter {
	return &BrowserPool_Expecter{mock: &_m.Mock}
}

// Checkout provides a mock function for the type BrowserPool
func (_mock *BrowserPool) Checkout(ctx context.Context, protocol models.BrowserProtocol, caps capabilities.Capabilities) (browser.Browser, error) {
	ret := _mock.Called(ctx, protocol, caps)

	if len(ret) == 0 {
		panic("no return value specified for Checkout")
	}

	var r0 browser.Browser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.BrowserProtocol, capabilities.Capabilities) (browser.Browser, error)); ok {
		return returnFunc(ctx, protocol, caps)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.BrowserProtocol, capabilities.Capabilities) browser.Browser); ok {
		r0 = returnFunc(ctx, protocol, caps)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(browser.Browser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.BrowserProtocol, capabilities.Capabilities) error); ok {
		r1 = returnFunc(ctx, protocol, caps)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BrowserPool_Checkout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Checkout'
type BrowserPool_Checkout_Call struct {
	*mock.Call
}

// Checkout is a helper method to define mock.On call
//   - ctx context.Context
//   - protocol models.BrowserProtocol
//   - caps capabilities.Capabilities
func (_e *BrowserPool_Expecter) Checkout(ctx interface{}, protocol interface{}, caps interface{}) *BrowserPool_Checkout_Call {
	return &BrowserPool_Checkout_Call{Call: _e.mock.On("Checkout", ctx, protocol, caps)}
}

func (_c *BrowserPool_Checkout_Call) Run(run func(ctx context.Context, protocol models.BrowserProtocol, caps capabilities.Capabilities)) *BrowserPool_Checkout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.BrowserProtocol
		if args[1] != nil {
			arg1 = args[1].(models.BrowserProtocol)
		}
		var arg2 capabilities.Capabilities
		if args[2] != nil {
			arg2 = args[2].(capabilities.Capabilities)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *BrowserPool_Checkout_Call) Return(browser1 browser.Browser, err error) *BrowserPool_Checkout_Call {
	_c.Call.Return(browser1, err)
	return _c
}

func (_c *BrowserPool_Checkout_Call) RunAndReturn(run func(ctx context.Context, protocol models.BrowserProtocol, caps capabilities.Capabilities) (browser.Browser, error)) *BrowserPool_Checkout_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type BrowserPool
func (_mock *BrowserPool) Shutdown(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// BrowserPool_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type BrowserPool_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *BrowserPool_Expecter) Shutdown(ctx interface{}) *BrowserPool_Shutdown_Call {
	return &BrowserPool_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *BrowserPool_Shutdown_Call) Run(run func(ctx context.Context)) *BrowserPool_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *BrowserPool_Shutdown_Call) Return(err error) *BrowserPool_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *BrowserPool_Shutdown_Call) RunAndReturn(run func(ctx context.Context) error) *BrowserPool_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}
