// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// NewBrowsersCatalogController creates a new instance of BrowsersCatalogController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBrowsersCatalogController(t interface {
	mock.TestingT
	Cleanup(func())
}) *BrowsersCatalogController {
	mock := &BrowsersCatalogController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BrowsersCatalogController is an autogenerated mock type for the BrowsersCatalogController type
type BrowsersCatalogController struct {
	mock.Mock
}

type BrowsersCatalogController_Expecter struct {
	mock *mock.Mock
}

func (_m *BrowsersCatalogController) EXPECT() *BrowsersCatalogController_Expecter {
	return &BrowsersCatalogController_Expecter{mock: &_m.Mock}
}

// Browsers provides a mock function for the type BrowsersCatalogController
func (_mock *BrowsersCatalogController) Browsers(c echo.Context) error {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Browsers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// BrowsersCatalogController_Browsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Browsers'
type BrowsersCatalogController_Browsers_Call struct {
	*mock.Call
}

// Browsers is a helper method to define mock.On call
//   - c echo.Context
func (_e *BrowsersCatalogController_Expecter) Browsers(c interface{}) *BrowsersCatalogController_Browsers_Call {
	return &BrowsersCatalogController_Browsers_Call{Call: _e.mock.On("Browsers", c)}
}

func (_c *BrowsersCatalogController_Browsers_Call) Run(run func(c echo.Context)) *BrowsersCatalogController_Browsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *BrowsersCatalogController_Browsers_Call) Return(err error) *BrowsersCatalogController_Browsers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *BrowsersCatalogController_Browsers_Call) RunAndReturn(run func(c echo.Context) error) *BrowsersCatalogController_Browsers_Call {
	_c.Call.Return(run)
	return _c
}
