// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/selebrow/selebrow/pkg/capabilities"
	"github.com/selebrow/selebrow/pkg/models"
	mock "github.com/stretchr/testify/mock"
	"k8s.io/api/core/v1"
)

// NewBrowserConverter creates a new instance of BrowserConverter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBrowserConverter(t interface {
	mock.TestingT
	Cleanup(func())
}) *BrowserConverter {
	mock := &BrowserConverter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BrowserConverter is an autogenerated mock type for the BrowserConverter type
type BrowserConverter struct {
	mock.Mock
}

type BrowserConverter_Expecter struct {
	mock *mock.Mock
}

func (_m *BrowserConverter) EXPECT() *BrowserConverter_Expecter {
	return &BrowserConverter_Expecter{mock: &_m.Mock}
}

// ToPod provides a mock function for the type BrowserConverter
func (_mock *BrowserConverter) ToPod(cfg models.BrowserImageConfig, caps capabilities.Capabilities) (v1.Pod, error) {
	ret := _mock.Called(cfg, caps)

	if len(ret) == 0 {
		panic("no return value specified for ToPod")
	}

	var r0 v1.Pod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(models.BrowserImageConfig, capabilities.Capabilities) (v1.Pod, error)); ok {
		return returnFunc(cfg, caps)
	}
	if returnFunc, ok := ret.Get(0).(func(models.BrowserImageConfig, capabilities.Capabilities) v1.Pod); ok {
		r0 = returnFunc(cfg, caps)
	} else {
		r0 = ret.Get(0).(v1.Pod)
	}
	if returnFunc, ok := ret.Get(1).(func(models.BrowserImageConfig, capabilities.Capabilities) error); ok {
		r1 = returnFunc(cfg, caps)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BrowserConverter_ToPod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToPod'
type BrowserConverter_ToPod_Call struct {
	*mock.Call
}

// ToPod is a helper method to define mock.On call
//   - cfg models.BrowserImageConfig
//   - caps capabilities.Capabilities
func (_e *BrowserConverter_Expecter) ToPod(cfg interface{}, caps interface{}) *BrowserConverter_ToPod_Call {
	return &BrowserConverter_ToPod_Call{Call: _e.mock.On("ToPod", cfg, caps)}
}

func (_c *BrowserConverter_ToPod_Call) Run(run func(cfg models.BrowserImageConfig, caps capabilities.Capabilities)) *BrowserConverter_ToPod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.BrowserImageConfig
		if args[0] != nil {
			arg0 = args[0].(models.BrowserImageConfig)
		}
		var arg1 capabilities.Capabilities
		if args[1] != nil {
			arg1 = args[1].(capabilities.Capabilities)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BrowserConverter_ToPod_Call) Return(pod v1.Pod, err error) *BrowserConverter_ToPod_Call {
	_c.Call.Return(pod, err)
	return _c
}

func (_c *BrowserConverter_ToPod_Call) RunAndReturn(run func(cfg models.BrowserImageConfig, caps capabilities.Capabilities) (v1.Pod, error)) *BrowserConverter_ToPod_Call {
	_c.Call.Return(run)
	return _c
}
