// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CIConfig is an autogenerated mock type for the CIConfig type
type CIConfig struct {
	mock.Mock
}

type CIConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *CIConfig) EXPECT() *CIConfig_Expecter {
	return &CIConfig_Expecter{mock: &_m.Mock}
}

// JobID provides a mock function with no fields
func (_m *CIConfig) JobID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for JobID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// CIConfig_JobID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JobID'
type CIConfig_JobID_Call struct {
	*mock.Call
}

// JobID is a helper method to define mock.On call
func (_e *CIConfig_Expecter) JobID() *CIConfig_JobID_Call {
	return &CIConfig_JobID_Call{Call: _e.mock.On("JobID")}
}

func (_c *CIConfig_JobID_Call) Run(run func()) *CIConfig_JobID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CIConfig_JobID_Call) Return(_a0 string) *CIConfig_JobID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CIConfig_JobID_Call) RunAndReturn(run func() string) *CIConfig_JobID_Call {
	_c.Call.Return(run)
	return _c
}

// ProjectName provides a mock function with no fields
func (_m *CIConfig) ProjectName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProjectName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// CIConfig_ProjectName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProjectName'
type CIConfig_ProjectName_Call struct {
	*mock.Call
}

// ProjectName is a helper method to define mock.On call
func (_e *CIConfig_Expecter) ProjectName() *CIConfig_ProjectName_Call {
	return &CIConfig_ProjectName_Call{Call: _e.mock.On("ProjectName")}
}

func (_c *CIConfig_ProjectName_Call) Run(run func()) *CIConfig_ProjectName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CIConfig_ProjectName_Call) Return(_a0 string) *CIConfig_ProjectName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CIConfig_ProjectName_Call) RunAndReturn(run func() string) *CIConfig_ProjectName_Call {
	_c.Call.Return(run)
	return _c
}

// ProjectNamespace provides a mock function with no fields
func (_m *CIConfig) ProjectNamespace() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProjectNamespace")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// CIConfig_ProjectNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProjectNamespace'
type CIConfig_ProjectNamespace_Call struct {
	*mock.Call
}

// ProjectNamespace is a helper method to define mock.On call
func (_e *CIConfig_Expecter) ProjectNamespace() *CIConfig_ProjectNamespace_Call {
	return &CIConfig_ProjectNamespace_Call{Call: _e.mock.On("ProjectNamespace")}
}

func (_c *CIConfig_ProjectNamespace_Call) Run(run func()) *CIConfig_ProjectNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CIConfig_ProjectNamespace_Call) Return(_a0 string) *CIConfig_ProjectNamespace_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CIConfig_ProjectNamespace_Call) RunAndReturn(run func() string) *CIConfig_ProjectNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// NewCIConfig creates a new instance of CIConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCIConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *CIConfig {
	mock := &CIConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
