// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net"

	mock "github.com/stretchr/testify/mock"
)

// NewConnFactory creates a new instance of ConnFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConnFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConnFactory {
	mock := &ConnFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ConnFactory is an autogenerated mock type for the ConnFactory type
type ConnFactory struct {
	mock.Mock
}

type ConnFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *ConnFactory) EXPECT() *ConnFactory_Expecter {
	return &ConnFactory_Expecter{mock: &_m.Mock}
}

// GetConn provides a mock function for the type ConnFactory
func (_mock *ConnFactory) GetConn(ctx context.Context, hostport string) (net.Conn, error) {
	ret := _mock.Called(ctx, hostport)

	if len(ret) == 0 {
		panic("no return value specified for GetConn")
	}

	var r0 net.Conn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (net.Conn, error)); ok {
		return returnFunc(ctx, hostport)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) net.Conn); ok {
		r0 = returnFunc(ctx, hostport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hostport)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ConnFactory_GetConn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConn'
type ConnFactory_GetConn_Call struct {
	*mock.Call
}

// GetConn is a helper method to define mock.On call
//   - ctx context.Context
//   - hostport string
func (_e *ConnFactory_Expecter) GetConn(ctx interface{}, hostport interface{}) *ConnFactory_GetConn_Call {
	return &ConnFactory_GetConn_Call{Call: _e.mock.On("GetConn", ctx, hostport)}
}

func (_c *ConnFactory_GetConn_Call) Run(run func(ctx context.Context, hostport string)) *ConnFactory_GetConn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ConnFactory_GetConn_Call) Return(conn net.Conn, err error) *ConnFactory_GetConn_Call {
	_c.Call.Return(conn, err)
	return _c
}

func (_c *ConnFactory_GetConn_Call) RunAndReturn(run func(ctx context.Context, hostport string) (net.Conn, error)) *ConnFactory_GetConn_Call {
	_c.Call.Return(run)
	return _c
}
