// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"
	net "net"

	mock "github.com/stretchr/testify/mock"
)

// ConnFactory is an autogenerated mock type for the ConnFactory type
type ConnFactory struct {
	mock.Mock
}

type ConnFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *ConnFactory) EXPECT() *ConnFactory_Expecter {
	return &ConnFactory_Expecter{mock: &_m.Mock}
}

// GetConn provides a mock function with given fields: ctx, hostport
func (_m *ConnFactory) GetConn(ctx context.Context, hostport string) (net.Conn, error) {
	ret := _m.Called(ctx, hostport)

	if len(ret) == 0 {
		panic("no return value specified for GetConn")
	}

	var r0 net.Conn
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (net.Conn, error)); ok {
		return rf(ctx, hostport)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) net.Conn); ok {
		r0 = rf(ctx, hostport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, hostport)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConnFactory_GetConn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConn'
type ConnFactory_GetConn_Call struct {
	*mock.Call
}

// GetConn is a helper method to define mock.On call
//   - ctx context.Context
//   - hostport string
func (_e *ConnFactory_Expecter) GetConn(ctx interface{}, hostport interface{}) *ConnFactory_GetConn_Call {
	return &ConnFactory_GetConn_Call{Call: _e.mock.On("GetConn", ctx, hostport)}
}

func (_c *ConnFactory_GetConn_Call) Run(run func(ctx context.Context, hostport string)) *ConnFactory_GetConn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ConnFactory_GetConn_Call) Return(_a0 net.Conn, _a1 error) *ConnFactory_GetConn_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConnFactory_GetConn_Call) RunAndReturn(run func(context.Context, string) (net.Conn, error)) *ConnFactory_GetConn_Call {
	_c.Call.Return(run)
	return _c
}

// NewConnFactory creates a new instance of ConnFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConnFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConnFactory {
	mock := &ConnFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
