// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net"

	mock "github.com/stretchr/testify/mock"
)

// NewContextDialer creates a new instance of ContextDialer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContextDialer(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContextDialer {
	mock := &ContextDialer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ContextDialer is an autogenerated mock type for the ContextDialer type
type ContextDialer struct {
	mock.Mock
}

type ContextDialer_Expecter struct {
	mock *mock.Mock
}

func (_m *ContextDialer) EXPECT() *ContextDialer_Expecter {
	return &ContextDialer_Expecter{mock: &_m.Mock}
}

// DialContext provides a mock function for the type ContextDialer
func (_mock *ContextDialer) DialContext(ctx context.Context, network string, address string) (net.Conn, error) {
	ret := _mock.Called(ctx, network, address)

	if len(ret) == 0 {
		panic("no return value specified for DialContext")
	}

	var r0 net.Conn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (net.Conn, error)); ok {
		return returnFunc(ctx, network, address)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) net.Conn); ok {
		r0 = returnFunc(ctx, network, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, network, address)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ContextDialer_DialContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DialContext'
type ContextDialer_DialContext_Call struct {
	*mock.Call
}

// DialContext is a helper method to define mock.On call
//   - ctx context.Context
//   - network string
//   - address string
func (_e *ContextDialer_Expecter) DialContext(ctx interface{}, network interface{}, address interface{}) *ContextDialer_DialContext_Call {
	return &ContextDialer_DialContext_Call{Call: _e.mock.On("DialContext", ctx, network, address)}
}

func (_c *ContextDialer_DialContext_Call) Run(run func(ctx context.Context, network string, address string)) *ContextDialer_DialContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ContextDialer_DialContext_Call) Return(conn net.Conn, err error) *ContextDialer_DialContext_Call {
	_c.Call.Return(conn, err)
	return _c
}

func (_c *ContextDialer_DialContext_Call) RunAndReturn(run func(ctx context.Context, network string, address string) (net.Conn, error)) *ContextDialer_DialContext_Call {
	_c.Call.Return(run)
	return _c
}
