// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/selebrow/selebrow/pkg/config"
	mock "github.com/stretchr/testify/mock"
)

// NewDockerConfig creates a new instance of DockerConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDockerConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *DockerConfig {
	mock := &DockerConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DockerConfig is an autogenerated mock type for the DockerConfig type
type DockerConfig struct {
	mock.Mock
}

type DockerConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *DockerConfig) EXPECT() *DockerConfig_Expecter {
	return &DockerConfig_Expecter{mock: &_m.Mock}
}

// DockerEnv provides a mock function for the type DockerConfig
func (_mock *DockerConfig) DockerEnv() map[string]string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DockerEnv")
	}

	var r0 map[string]string
	if returnFunc, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	return r0
}

// DockerConfig_DockerEnv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DockerEnv'
type DockerConfig_DockerEnv_Call struct {
	*mock.Call
}

// DockerEnv is a helper method to define mock.On call
func (_e *DockerConfig_Expecter) DockerEnv() *DockerConfig_DockerEnv_Call {
	return &DockerConfig_DockerEnv_Call{Call: _e.mock.On("DockerEnv")}
}

func (_c *DockerConfig_DockerEnv_Call) Run(run func()) *DockerConfig_DockerEnv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DockerConfig_DockerEnv_Call) Return(stringToString map[string]string) *DockerConfig_DockerEnv_Call {
	_c.Call.Return(stringToString)
	return _c
}

func (_c *DockerConfig_DockerEnv_Call) RunAndReturn(run func() map[string]string) *DockerConfig_DockerEnv_Call {
	_c.Call.Return(run)
	return _c
}

// DockerNetwork provides a mock function for the type DockerConfig
func (_mock *DockerConfig) DockerNetwork() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DockerNetwork")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// DockerConfig_DockerNetwork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DockerNetwork'
type DockerConfig_DockerNetwork_Call struct {
	*mock.Call
}

// DockerNetwork is a helper method to define mock.On call
func (_e *DockerConfig_Expecter) DockerNetwork() *DockerConfig_DockerNetwork_Call {
	return &DockerConfig_DockerNetwork_Call{Call: _e.mock.On("DockerNetwork")}
}

func (_c *DockerConfig_DockerNetwork_Call) Run(run func()) *DockerConfig_DockerNetwork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DockerConfig_DockerNetwork_Call) Return(s string) *DockerConfig_DockerNetwork_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *DockerConfig_DockerNetwork_Call) RunAndReturn(run func() string) *DockerConfig_DockerNetwork_Call {
	_c.Call.Return(run)
	return _c
}

// DockerPlatform provides a mock function for the type DockerConfig
func (_mock *DockerConfig) DockerPlatform() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DockerPlatform")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// DockerConfig_DockerPlatform_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DockerPlatform'
type DockerConfig_DockerPlatform_Call struct {
	*mock.Call
}

// DockerPlatform is a helper method to define mock.On call
func (_e *DockerConfig_Expecter) DockerPlatform() *DockerConfig_DockerPlatform_Call {
	return &DockerConfig_DockerPlatform_Call{Call: _e.mock.On("DockerPlatform")}
}

func (_c *DockerConfig_DockerPlatform_Call) Run(run func()) *DockerConfig_DockerPlatform_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DockerConfig_DockerPlatform_Call) Return(s string) *DockerConfig_DockerPlatform_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *DockerConfig_DockerPlatform_Call) RunAndReturn(run func() string) *DockerConfig_DockerPlatform_Call {
	_c.Call.Return(run)
	return _c
}

// DockerPortMapping provides a mock function for the type DockerConfig
func (_mock *DockerConfig) DockerPortMapping() config.PortMappingMode {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DockerPortMapping")
	}

	var r0 config.PortMappingMode
	if returnFunc, ok := ret.Get(0).(func() config.PortMappingMode); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(config.PortMappingMode)
	}
	return r0
}

// DockerConfig_DockerPortMapping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DockerPortMapping'
type DockerConfig_DockerPortMapping_Call struct {
	*mock.Call
}

// DockerPortMapping is a helper method to define mock.On call
func (_e *DockerConfig_Expecter) DockerPortMapping() *DockerConfig_DockerPortMapping_Call {
	return &DockerConfig_DockerPortMapping_Call{Call: _e.mock.On("DockerPortMapping")}
}

func (_c *DockerConfig_DockerPortMapping_Call) Run(run func()) *DockerConfig_DockerPortMapping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DockerConfig_DockerPortMapping_Call) Return(portMappingMode config.PortMappingMode) *DockerConfig_DockerPortMapping_Call {
	_c.Call.Return(portMappingMode)
	return _c
}

func (_c *DockerConfig_DockerPortMapping_Call) RunAndReturn(run func() config.PortMappingMode) *DockerConfig_DockerPortMapping_Call {
	_c.Call.Return(run)
	return _c
}

// DockerPrivileged provides a mock function for the type DockerConfig
func (_mock *DockerConfig) DockerPrivileged() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DockerPrivileged")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// DockerConfig_DockerPrivileged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DockerPrivileged'
type DockerConfig_DockerPrivileged_Call struct {
	*mock.Call
}

// DockerPrivileged is a helper method to define mock.On call
func (_e *DockerConfig_Expecter) DockerPrivileged() *DockerConfig_DockerPrivileged_Call {
	return &DockerConfig_DockerPrivileged_Call{Call: _e.mock.On("DockerPrivileged")}
}

func (_c *DockerConfig_DockerPrivileged_Call) Run(run func()) *DockerConfig_DockerPrivileged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DockerConfig_DockerPrivileged_Call) Return(b bool) *DockerConfig_DockerPrivileged_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *DockerConfig_DockerPrivileged_Call) RunAndReturn(run func() bool) *DockerConfig_DockerPrivileged_Call {
	_c.Call.Return(run)
	return _c
}

// DockerPullImages provides a mock function for the type DockerConfig
func (_mock *DockerConfig) DockerPullImages() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DockerPullImages")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// DockerConfig_DockerPullImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DockerPullImages'
type DockerConfig_DockerPullImages_Call struct {
	*mock.Call
}

// DockerPullImages is a helper method to define mock.On call
func (_e *DockerConfig_Expecter) DockerPullImages() *DockerConfig_DockerPullImages_Call {
	return &DockerConfig_DockerPullImages_Call{Call: _e.mock.On("DockerPullImages")}
}

func (_c *DockerConfig_DockerPullImages_Call) Run(run func()) *DockerConfig_DockerPullImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DockerConfig_DockerPullImages_Call) Return(b bool) *DockerConfig_DockerPullImages_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *DockerConfig_DockerPullImages_Call) RunAndReturn(run func() bool) *DockerConfig_DockerPullImages_Call {
	_c.Call.Return(run)
	return _c
}
