// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/selebrow/selebrow/pkg/event/models"
	mock "github.com/stretchr/testify/mock"
)

// NewEventBroker creates a new instance of EventBroker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventBroker(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventBroker {
	mock := &EventBroker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EventBroker is an autogenerated mock type for the EventBroker type
type EventBroker struct {
	mock.Mock
}

type EventBroker_Expecter struct {
	mock *mock.Mock
}

func (_m *EventBroker) EXPECT() *EventBroker_Expecter {
	return &EventBroker_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type EventBroker
func (_mock *EventBroker) Publish(event models.IEvent) {
	_mock.Called(event)
	return
}

// EventBroker_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type EventBroker_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - event models.IEvent
func (_e *EventBroker_Expecter) Publish(event interface{}) *EventBroker_Publish_Call {
	return &EventBroker_Publish_Call{Call: _e.mock.On("Publish", event)}
}

func (_c *EventBroker_Publish_Call) Run(run func(event models.IEvent)) *EventBroker_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.IEvent
		if args[0] != nil {
			arg0 = args[0].(models.IEvent)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EventBroker_Publish_Call) Return() *EventBroker_Publish_Call {
	_c.Call.Return()
	return _c
}

func (_c *EventBroker_Publish_Call) RunAndReturn(run func(event models.IEvent)) *EventBroker_Publish_Call {
	_c.Run(run)
	return _c
}

// Subscribe provides a mock function for the type EventBroker
func (_mock *EventBroker) Subscribe(eventTypes ...string) <-chan models.IEvent {
	var tmpRet mock.Arguments
	if len(eventTypes) > 0 {
		tmpRet = _mock.Called(eventTypes)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan models.IEvent
	if returnFunc, ok := ret.Get(0).(func(...string) <-chan models.IEvent); ok {
		r0 = returnFunc(eventTypes...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan models.IEvent)
		}
	}
	return r0
}

// EventBroker_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type EventBroker_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - eventTypes ...string
func (_e *EventBroker_Expecter) Subscribe(eventTypes ...interface{}) *EventBroker_Subscribe_Call {
	return &EventBroker_Subscribe_Call{Call: _e.mock.On("Subscribe",
		append([]interface{}{}, eventTypes...)...)}
}

func (_c *EventBroker_Subscribe_Call) Run(run func(eventTypes ...string)) *EventBroker_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		var variadicArgs []string
		if len(args) > 0 {
			variadicArgs = args[0].([]string)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *EventBroker_Subscribe_Call) Return(iEventCh <-chan models.IEvent) *EventBroker_Subscribe_Call {
	_c.Call.Return(iEventCh)
	return _c
}

func (_c *EventBroker_Subscribe_Call) RunAndReturn(run func(eventTypes ...string) <-chan models.IEvent) *EventBroker_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}
