// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"k8s.io/api/core/v1"
	v10 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/watch"
)

// NewKubernetesClient creates a new instance of KubernetesClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKubernetesClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *KubernetesClient {
	mock := &KubernetesClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// KubernetesClient is an autogenerated mock type for the KubernetesClient type
type KubernetesClient struct {
	mock.Mock
}

type KubernetesClient_Expecter struct {
	mock *mock.Mock
}

func (_m *KubernetesClient) EXPECT() *KubernetesClient_Expecter {
	return &KubernetesClient_Expecter{mock: &_m.Mock}
}

// ClusterModeOut provides a mock function for the type KubernetesClient
func (_mock *KubernetesClient) ClusterModeOut() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ClusterModeOut")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// KubernetesClient_ClusterModeOut_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClusterModeOut'
type KubernetesClient_ClusterModeOut_Call struct {
	*mock.Call
}

// ClusterModeOut is a helper method to define mock.On call
func (_e *KubernetesClient_Expecter) ClusterModeOut() *KubernetesClient_ClusterModeOut_Call {
	return &KubernetesClient_ClusterModeOut_Call{Call: _e.mock.On("ClusterModeOut")}
}

func (_c *KubernetesClient_ClusterModeOut_Call) Run(run func()) *KubernetesClient_ClusterModeOut_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *KubernetesClient_ClusterModeOut_Call) Return(b bool) *KubernetesClient_ClusterModeOut_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *KubernetesClient_ClusterModeOut_Call) RunAndReturn(run func() bool) *KubernetesClient_ClusterModeOut_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePod provides a mock function for the type KubernetesClient
func (_mock *KubernetesClient) CreatePod(ctx context.Context, pod *v1.Pod) (*v1.Pod, error) {
	ret := _mock.Called(ctx, pod)

	if len(ret) == 0 {
		panic("no return value specified for CreatePod")
	}

	var r0 *v1.Pod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.Pod) (*v1.Pod, error)); ok {
		return returnFunc(ctx, pod)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.Pod) *v1.Pod); ok {
		r0 = returnFunc(ctx, pod)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Pod)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.Pod) error); ok {
		r1 = returnFunc(ctx, pod)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KubernetesClient_CreatePod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePod'
type KubernetesClient_CreatePod_Call struct {
	*mock.Call
}

// CreatePod is a helper method to define mock.On call
//   - ctx context.Context
//   - pod *v1.Pod
func (_e *KubernetesClient_Expecter) CreatePod(ctx interface{}, pod interface{}) *KubernetesClient_CreatePod_Call {
	return &KubernetesClient_CreatePod_Call{Call: _e.mock.On("CreatePod", ctx, pod)}
}

func (_c *KubernetesClient_CreatePod_Call) Run(run func(ctx context.Context, pod *v1.Pod)) *KubernetesClient_CreatePod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.Pod
		if args[1] != nil {
			arg1 = args[1].(*v1.Pod)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *KubernetesClient_CreatePod_Call) Return(pod1 *v1.Pod, err error) *KubernetesClient_CreatePod_Call {
	_c.Call.Return(pod1, err)
	return _c
}

func (_c *KubernetesClient_CreatePod_Call) RunAndReturn(run func(ctx context.Context, pod *v1.Pod) (*v1.Pod, error)) *KubernetesClient_CreatePod_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePod provides a mock function for the type KubernetesClient
func (_mock *KubernetesClient) DeletePod(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DeletePod")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// KubernetesClient_DeletePod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePod'
type KubernetesClient_DeletePod_Call struct {
	*mock.Call
}

// DeletePod is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *KubernetesClient_Expecter) DeletePod(ctx interface{}, name interface{}) *KubernetesClient_DeletePod_Call {
	return &KubernetesClient_DeletePod_Call{Call: _e.mock.On("DeletePod", ctx, name)}
}

func (_c *KubernetesClient_DeletePod_Call) Run(run func(ctx context.Context, name string)) *KubernetesClient_DeletePod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *KubernetesClient_DeletePod_Call) Return(err error) *KubernetesClient_DeletePod_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *KubernetesClient_DeletePod_Call) RunAndReturn(run func(ctx context.Context, name string) error) *KubernetesClient_DeletePod_Call {
	_c.Call.Return(run)
	return _c
}

// ListPods provides a mock function for the type KubernetesClient
func (_mock *KubernetesClient) ListPods(ctx context.Context, selector *v10.LabelSelector) (*v1.PodList, error) {
	ret := _mock.Called(ctx, selector)

	if len(ret) == 0 {
		panic("no return value specified for ListPods")
	}

	var r0 *v1.PodList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v10.LabelSelector) (*v1.PodList, error)); ok {
		return returnFunc(ctx, selector)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v10.LabelSelector) *v1.PodList); ok {
		r0 = returnFunc(ctx, selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.PodList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v10.LabelSelector) error); ok {
		r1 = returnFunc(ctx, selector)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KubernetesClient_ListPods_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPods'
type KubernetesClient_ListPods_Call struct {
	*mock.Call
}

// ListPods is a helper method to define mock.On call
//   - ctx context.Context
//   - selector *v10.LabelSelector
func (_e *KubernetesClient_Expecter) ListPods(ctx interface{}, selector interface{}) *KubernetesClient_ListPods_Call {
	return &KubernetesClient_ListPods_Call{Call: _e.mock.On("ListPods", ctx, selector)}
}

func (_c *KubernetesClient_ListPods_Call) Run(run func(ctx context.Context, selector *v10.LabelSelector)) *KubernetesClient_ListPods_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v10.LabelSelector
		if args[1] != nil {
			arg1 = args[1].(*v10.LabelSelector)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *KubernetesClient_ListPods_Call) Return(podList *v1.PodList, err error) *KubernetesClient_ListPods_Call {
	_c.Call.Return(podList, err)
	return _c
}

func (_c *KubernetesClient_ListPods_Call) RunAndReturn(run func(ctx context.Context, selector *v10.LabelSelector) (*v1.PodList, error)) *KubernetesClient_ListPods_Call {
	_c.Call.Return(run)
	return _c
}

// PortForwardPod provides a mock function for the type KubernetesClient
func (_mock *KubernetesClient) PortForwardPod(podName string, podPort int64, localport int64, stopCh chan struct{}) error {
	ret := _mock.Called(podName, podPort, localport, stopCh)

	if len(ret) == 0 {
		panic("no return value specified for PortForwardPod")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, int64, int64, chan struct{}) error); ok {
		r0 = returnFunc(podName, podPort, localport, stopCh)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// KubernetesClient_PortForwardPod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PortForwardPod'
type KubernetesClient_PortForwardPod_Call struct {
	*mock.Call
}

// PortForwardPod is a helper method to define mock.On call
//   - podName string
//   - podPort int64
//   - localport int64
//   - stopCh chan struct{}
func (_e *KubernetesClient_Expecter) PortForwardPod(podName interface{}, podPort interface{}, localport interface{}, stopCh interface{}) *KubernetesClient_PortForwardPod_Call {
	return &KubernetesClient_PortForwardPod_Call{Call: _e.mock.On("PortForwardPod", podName, podPort, localport, stopCh)}
}

func (_c *KubernetesClient_PortForwardPod_Call) Run(run func(podName string, podPort int64, localport int64, stopCh chan struct{})) *KubernetesClient_PortForwardPod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 chan struct{}
		if args[3] != nil {
			arg3 = args[3].(chan struct{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *KubernetesClient_PortForwardPod_Call) Return(err error) *KubernetesClient_PortForwardPod_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *KubernetesClient_PortForwardPod_Call) RunAndReturn(run func(podName string, podPort int64, localport int64, stopCh chan struct{}) error) *KubernetesClient_PortForwardPod_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function for the type KubernetesClient
func (_mock *KubernetesClient) Watch(ctx context.Context, selector *v10.LabelSelector) (<-chan *watch.Event, error) {
	ret := _mock.Called(ctx, selector)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 <-chan *watch.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v10.LabelSelector) (<-chan *watch.Event, error)); ok {
		return returnFunc(ctx, selector)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v10.LabelSelector) <-chan *watch.Event); ok {
		r0 = returnFunc(ctx, selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *watch.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v10.LabelSelector) error); ok {
		r1 = returnFunc(ctx, selector)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KubernetesClient_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type KubernetesClient_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - selector *v10.LabelSelector
func (_e *KubernetesClient_Expecter) Watch(ctx interface{}, selector interface{}) *KubernetesClient_Watch_Call {
	return &KubernetesClient_Watch_Call{Call: _e.mock.On("Watch", ctx, selector)}
}

func (_c *KubernetesClient_Watch_Call) Run(run func(ctx context.Context, selector *v10.LabelSelector)) *KubernetesClient_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v10.LabelSelector
		if args[1] != nil {
			arg1 = args[1].(*v10.LabelSelector)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *KubernetesClient_Watch_Call) Return(eventCh <-chan *watch.Event, err error) *KubernetesClient_Watch_Call {
	_c.Call.Return(eventCh, err)
	return _c
}

func (_c *KubernetesClient_Watch_Call) RunAndReturn(run func(ctx context.Context, selector *v10.LabelSelector) (<-chan *watch.Event, error)) *KubernetesClient_Watch_Call {
	_c.Call.Return(run)
	return _c
}
