// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// NowFunc is an autogenerated mock type for the NowFunc type
type NowFunc struct {
	mock.Mock
}

type NowFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *NowFunc) EXPECT() *NowFunc_Expecter {
	return &NowFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with no fields
func (_m *NowFunc) Execute() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// NowFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type NowFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *NowFunc_Expecter) Execute() *NowFunc_Execute_Call {
	return &NowFunc_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *NowFunc_Execute_Call) Run(run func()) *NowFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NowFunc_Execute_Call) Return(_a0 time.Time) *NowFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NowFunc_Execute_Call) RunAndReturn(run func() time.Time) *NowFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewNowFunc creates a new instance of NowFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNowFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *NowFunc {
	mock := &NowFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
