// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewPodWatcher creates a new instance of PodWatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPodWatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *PodWatcher {
	mock := &PodWatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PodWatcher is an autogenerated mock type for the PodWatcher type
type PodWatcher struct {
	mock.Mock
}

type PodWatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *PodWatcher) EXPECT() *PodWatcher_Expecter {
	return &PodWatcher_Expecter{mock: &_m.Mock}
}

// WaitPodReady provides a mock function for the type PodWatcher
func (_mock *PodWatcher) WaitPodReady(ctx context.Context, podName string) (string, error) {
	ret := _mock.Called(ctx, podName)

	if len(ret) == 0 {
		panic("no return value specified for WaitPodReady")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, podName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, podName)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, podName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PodWatcher_WaitPodReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitPodReady'
type PodWatcher_WaitPodReady_Call struct {
	*mock.Call
}

// WaitPodReady is a helper method to define mock.On call
//   - ctx context.Context
//   - podName string
func (_e *PodWatcher_Expecter) WaitPodReady(ctx interface{}, podName interface{}) *PodWatcher_WaitPodReady_Call {
	return &PodWatcher_WaitPodReady_Call{Call: _e.mock.On("WaitPodReady", ctx, podName)}
}

func (_c *PodWatcher_WaitPodReady_Call) Run(run func(ctx context.Context, podName string)) *PodWatcher_WaitPodReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PodWatcher_WaitPodReady_Call) Return(s string, err error) *PodWatcher_WaitPodReady_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *PodWatcher_WaitPodReady_Call) RunAndReturn(run func(ctx context.Context, podName string) (string, error)) *PodWatcher_WaitPodReady_Call {
	_c.Call.Return(run)
	return _c
}
