// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	"github.com/selebrow/selebrow/pkg/config"
	mock "github.com/stretchr/testify/mock"
	"go.uber.org/zap/zapcore"
)

// NewProxyConfig creates a new instance of ProxyConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProxyConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProxyConfig {
	mock := &ProxyConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProxyConfig is an autogenerated mock type for the ProxyConfig type
type ProxyConfig struct {
	mock.Mock
}

type ProxyConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *ProxyConfig) EXPECT() *ProxyConfig_Expecter {
	return &ProxyConfig_Expecter{mock: &_m.Mock}
}

// ProxyAccessLogLevel provides a mock function for the type ProxyConfig
func (_mock *ProxyConfig) ProxyAccessLogLevel() zapcore.Level {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProxyAccessLogLevel")
	}

	var r0 zapcore.Level
	if returnFunc, ok := ret.Get(0).(func() zapcore.Level); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(zapcore.Level)
	}
	return r0
}

// ProxyConfig_ProxyAccessLogLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProxyAccessLogLevel'
type ProxyConfig_ProxyAccessLogLevel_Call struct {
	*mock.Call
}

// ProxyAccessLogLevel is a helper method to define mock.On call
func (_e *ProxyConfig_Expecter) ProxyAccessLogLevel() *ProxyConfig_ProxyAccessLogLevel_Call {
	return &ProxyConfig_ProxyAccessLogLevel_Call{Call: _e.mock.On("ProxyAccessLogLevel")}
}

func (_c *ProxyConfig_ProxyAccessLogLevel_Call) Run(run func()) *ProxyConfig_ProxyAccessLogLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProxyConfig_ProxyAccessLogLevel_Call) Return(level zapcore.Level) *ProxyConfig_ProxyAccessLogLevel_Call {
	_c.Call.Return(level)
	return _c
}

func (_c *ProxyConfig_ProxyAccessLogLevel_Call) RunAndReturn(run func() zapcore.Level) *ProxyConfig_ProxyAccessLogLevel_Call {
	_c.Call.Return(run)
	return _c
}

// ProxyConnectTimeout provides a mock function for the type ProxyConfig
func (_mock *ProxyConfig) ProxyConnectTimeout() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProxyConnectTimeout")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// ProxyConfig_ProxyConnectTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProxyConnectTimeout'
type ProxyConfig_ProxyConnectTimeout_Call struct {
	*mock.Call
}

// ProxyConnectTimeout is a helper method to define mock.On call
func (_e *ProxyConfig_Expecter) ProxyConnectTimeout() *ProxyConfig_ProxyConnectTimeout_Call {
	return &ProxyConfig_ProxyConnectTimeout_Call{Call: _e.mock.On("ProxyConnectTimeout")}
}

func (_c *ProxyConfig_ProxyConnectTimeout_Call) Run(run func()) *ProxyConfig_ProxyConnectTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProxyConfig_ProxyConnectTimeout_Call) Return(duration time.Duration) *ProxyConfig_ProxyConnectTimeout_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *ProxyConfig_ProxyConnectTimeout_Call) RunAndReturn(run func() time.Duration) *ProxyConfig_ProxyConnectTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// ProxyEnabled provides a mock function for the type ProxyConfig
func (_mock *ProxyConfig) ProxyEnabled() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProxyEnabled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// ProxyConfig_ProxyEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProxyEnabled'
type ProxyConfig_ProxyEnabled_Call struct {
	*mock.Call
}

// ProxyEnabled is a helper method to define mock.On call
func (_e *ProxyConfig_Expecter) ProxyEnabled() *ProxyConfig_ProxyEnabled_Call {
	return &ProxyConfig_ProxyEnabled_Call{Call: _e.mock.On("ProxyEnabled")}
}

func (_c *ProxyConfig_ProxyEnabled_Call) Run(run func()) *ProxyConfig_ProxyEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProxyConfig_ProxyEnabled_Call) Return(b bool) *ProxyConfig_ProxyEnabled_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *ProxyConfig_ProxyEnabled_Call) RunAndReturn(run func() bool) *ProxyConfig_ProxyEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// ProxyListen provides a mock function for the type ProxyConfig
func (_mock *ProxyConfig) ProxyListen() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProxyListen")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ProxyConfig_ProxyListen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProxyListen'
type ProxyConfig_ProxyListen_Call struct {
	*mock.Call
}

// ProxyListen is a helper method to define mock.On call
func (_e *ProxyConfig_Expecter) ProxyListen() *ProxyConfig_ProxyListen_Call {
	return &ProxyConfig_ProxyListen_Call{Call: _e.mock.On("ProxyListen")}
}

func (_c *ProxyConfig_ProxyListen_Call) Run(run func()) *ProxyConfig_ProxyListen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProxyConfig_ProxyListen_Call) Return(s string) *ProxyConfig_ProxyListen_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ProxyConfig_ProxyListen_Call) RunAndReturn(run func() string) *ProxyConfig_ProxyListen_Call {
	_c.Call.Return(run)
	return _c
}

// ProxyOpts provides a mock function for the type ProxyConfig
func (_mock *ProxyConfig) ProxyOpts(defaultProxyHostFn config.ProxyHostFunc) (*config.ProxyOpts, error) {
	ret := _mock.Called(defaultProxyHostFn)

	if len(ret) == 0 {
		panic("no return value specified for ProxyOpts")
	}

	var r0 *config.ProxyOpts
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(config.ProxyHostFunc) (*config.ProxyOpts, error)); ok {
		return returnFunc(defaultProxyHostFn)
	}
	if returnFunc, ok := ret.Get(0).(func(config.ProxyHostFunc) *config.ProxyOpts); ok {
		r0 = returnFunc(defaultProxyHostFn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.ProxyOpts)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(config.ProxyHostFunc) error); ok {
		r1 = returnFunc(defaultProxyHostFn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProxyConfig_ProxyOpts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProxyOpts'
type ProxyConfig_ProxyOpts_Call struct {
	*mock.Call
}

// ProxyOpts is a helper method to define mock.On call
//   - defaultProxyHostFn config.ProxyHostFunc
func (_e *ProxyConfig_Expecter) ProxyOpts(defaultProxyHostFn interface{}) *ProxyConfig_ProxyOpts_Call {
	return &ProxyConfig_ProxyOpts_Call{Call: _e.mock.On("ProxyOpts", defaultProxyHostFn)}
}

func (_c *ProxyConfig_ProxyOpts_Call) Run(run func(defaultProxyHostFn config.ProxyHostFunc)) *ProxyConfig_ProxyOpts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.ProxyHostFunc
		if args[0] != nil {
			arg0 = args[0].(config.ProxyHostFunc)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ProxyConfig_ProxyOpts_Call) Return(proxyOpts *config.ProxyOpts, err error) *ProxyConfig_ProxyOpts_Call {
	_c.Call.Return(proxyOpts, err)
	return _c
}

func (_c *ProxyConfig_ProxyOpts_Call) RunAndReturn(run func(defaultProxyHostFn config.ProxyHostFunc) (*config.ProxyOpts, error)) *ProxyConfig_ProxyOpts_Call {
	_c.Call.Return(run)
	return _c
}

// ProxyResolveHost provides a mock function for the type ProxyConfig
func (_mock *ProxyConfig) ProxyResolveHost() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProxyResolveHost")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// ProxyConfig_ProxyResolveHost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProxyResolveHost'
type ProxyConfig_ProxyResolveHost_Call struct {
	*mock.Call
}

// ProxyResolveHost is a helper method to define mock.On call
func (_e *ProxyConfig_Expecter) ProxyResolveHost() *ProxyConfig_ProxyResolveHost_Call {
	return &ProxyConfig_ProxyResolveHost_Call{Call: _e.mock.On("ProxyResolveHost")}
}

func (_c *ProxyConfig_ProxyResolveHost_Call) Run(run func()) *ProxyConfig_ProxyResolveHost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProxyConfig_ProxyResolveHost_Call) Return(b bool) *ProxyConfig_ProxyResolveHost_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *ProxyConfig_ProxyResolveHost_Call) RunAndReturn(run func() bool) *ProxyConfig_ProxyResolveHost_Call {
	_c.Call.Return(run)
	return _c
}
