// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// NewQuotaController creates a new instance of QuotaController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuotaController(t interface {
	mock.TestingT
	Cleanup(func())
}) *QuotaController {
	mock := &QuotaController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// QuotaController is an autogenerated mock type for the QuotaController type
type QuotaController struct {
	mock.Mock
}

type QuotaController_Expecter struct {
	mock *mock.Mock
}

func (_m *QuotaController) EXPECT() *QuotaController_Expecter {
	return &QuotaController_Expecter{mock: &_m.Mock}
}

// QuotaUsage provides a mock function for the type QuotaController
func (_mock *QuotaController) QuotaUsage(c echo.Context) error {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for QuotaUsage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// QuotaController_QuotaUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QuotaUsage'
type QuotaController_QuotaUsage_Call struct {
	*mock.Call
}

// QuotaUsage is a helper method to define mock.On call
//   - c echo.Context
func (_e *QuotaController_Expecter) QuotaUsage(c interface{}) *QuotaController_QuotaUsage_Call {
	return &QuotaController_QuotaUsage_Call{Call: _e.mock.On("QuotaUsage", c)}
}

func (_c *QuotaController_QuotaUsage_Call) Run(run func(c echo.Context)) *QuotaController_QuotaUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *QuotaController_QuotaUsage_Call) Return(err error) *QuotaController_QuotaUsage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *QuotaController_QuotaUsage_Call) RunAndReturn(run func(c echo.Context) error) *QuotaController_QuotaUsage_Call {
	_c.Call.Return(run)
	return _c
}
