// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/selebrow/selebrow/pkg/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewQuotaService creates a new instance of QuotaService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuotaService(t interface {
	mock.TestingT
	Cleanup(func())
}) *QuotaService {
	mock := &QuotaService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// QuotaService is an autogenerated mock type for the QuotaService type
type QuotaService struct {
	mock.Mock
}

type QuotaService_Expecter struct {
	mock *mock.Mock
}

func (_m *QuotaService) EXPECT() *QuotaService_Expecter {
	return &QuotaService_Expecter{mock: &_m.Mock}
}

// GetQuotaUsage provides a mock function for the type QuotaService
func (_mock *QuotaService) GetQuotaUsage() *dto.QuotaUsage {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetQuotaUsage")
	}

	var r0 *dto.QuotaUsage
	if returnFunc, ok := ret.Get(0).(func() *dto.QuotaUsage); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.QuotaUsage)
		}
	}
	return r0
}

// QuotaService_GetQuotaUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuotaUsage'
type QuotaService_GetQuotaUsage_Call struct {
	*mock.Call
}

// GetQuotaUsage is a helper method to define mock.On call
func (_e *QuotaService_Expecter) GetQuotaUsage() *QuotaService_GetQuotaUsage_Call {
	return &QuotaService_GetQuotaUsage_Call{Call: _e.mock.On("GetQuotaUsage")}
}

func (_c *QuotaService_GetQuotaUsage_Call) Run(run func()) *QuotaService_GetQuotaUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *QuotaService_GetQuotaUsage_Call) Return(quotaUsage *dto.QuotaUsage) *QuotaService_GetQuotaUsage_Call {
	_c.Call.Return(quotaUsage)
	return _c
}

func (_c *QuotaService_GetQuotaUsage_Call) RunAndReturn(run func() *dto.QuotaUsage) *QuotaService_GetQuotaUsage_Call {
	_c.Call.Return(run)
	return _c
}
