// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ReleaseFunc is an autogenerated mock type for the ReleaseFunc type
type ReleaseFunc struct {
	mock.Mock
}

type ReleaseFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *ReleaseFunc) EXPECT() *ReleaseFunc_Expecter {
	return &ReleaseFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with no fields
func (_m *ReleaseFunc) Execute() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// ReleaseFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ReleaseFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *ReleaseFunc_Expecter) Execute() *ReleaseFunc_Execute_Call {
	return &ReleaseFunc_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *ReleaseFunc_Execute_Call) Run(run func()) *ReleaseFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ReleaseFunc_Execute_Call) Return(_a0 int) *ReleaseFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReleaseFunc_Execute_Call) RunAndReturn(run func() int) *ReleaseFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewReleaseFunc creates a new instance of ReleaseFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReleaseFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReleaseFunc {
	mock := &ReleaseFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
