// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io"

	"github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// NewRenderer creates a new instance of Renderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Renderer {
	mock := &Renderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Renderer is an autogenerated mock type for the Renderer type
type Renderer struct {
	mock.Mock
}

type Renderer_Expecter struct {
	mock *mock.Mock
}

func (_m *Renderer) EXPECT() *Renderer_Expecter {
	return &Renderer_Expecter{mock: &_m.Mock}
}

// Render provides a mock function for the type Renderer
func (_mock *Renderer) Render(writer io.Writer, s string, ifaceVal interface{}, context echo.Context) error {
	ret := _mock.Called(writer, s, ifaceVal, context)

	if len(ret) == 0 {
		panic("no return value specified for Render")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(io.Writer, string, interface{}, echo.Context) error); ok {
		r0 = returnFunc(writer, s, ifaceVal, context)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Renderer_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type Renderer_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
//   - writer io.Writer
//   - s string
//   - ifaceVal interface{}
//   - context echo.Context
func (_e *Renderer_Expecter) Render(writer interface{}, s interface{}, ifaceVal interface{}, context interface{}) *Renderer_Render_Call {
	return &Renderer_Render_Call{Call: _e.mock.On("Render", writer, s, ifaceVal, context)}
}

func (_c *Renderer_Render_Call) Run(run func(writer io.Writer, s string, ifaceVal interface{}, context echo.Context)) *Renderer_Render_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Writer
		if args[0] != nil {
			arg0 = args[0].(io.Writer)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 echo.Context
		if args[3] != nil {
			arg3 = args[3].(echo.Context)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Renderer_Render_Call) Return(err error) *Renderer_Render_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Renderer_Render_Call) RunAndReturn(run func(writer io.Writer, s string, ifaceVal interface{}, context echo.Context) error) *Renderer_Render_Call {
	_c.Call.Return(run)
	return _c
}
