// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"bufio"
	"net"
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewResponseWriterHijacker creates a new instance of ResponseWriterHijacker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResponseWriterHijacker(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResponseWriterHijacker {
	mock := &ResponseWriterHijacker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ResponseWriterHijacker is an autogenerated mock type for the ResponseWriterHijacker type
type ResponseWriterHijacker struct {
	mock.Mock
}

type ResponseWriterHijacker_Expecter struct {
	mock *mock.Mock
}

func (_m *ResponseWriterHijacker) EXPECT() *ResponseWriterHijacker_Expecter {
	return &ResponseWriterHijacker_Expecter{mock: &_m.Mock}
}

// Header provides a mock function for the type ResponseWriterHijacker
func (_mock *ResponseWriterHijacker) Header() http.Header {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Header")
	}

	var r0 http.Header
	if returnFunc, ok := ret.Get(0).(func() http.Header); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Header)
		}
	}
	return r0
}

// ResponseWriterHijacker_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type ResponseWriterHijacker_Header_Call struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
func (_e *ResponseWriterHijacker_Expecter) Header() *ResponseWriterHijacker_Header_Call {
	return &ResponseWriterHijacker_Header_Call{Call: _e.mock.On("Header")}
}

func (_c *ResponseWriterHijacker_Header_Call) Run(run func()) *ResponseWriterHijacker_Header_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ResponseWriterHijacker_Header_Call) Return(header http.Header) *ResponseWriterHijacker_Header_Call {
	_c.Call.Return(header)
	return _c
}

func (_c *ResponseWriterHijacker_Header_Call) RunAndReturn(run func() http.Header) *ResponseWriterHijacker_Header_Call {
	_c.Call.Return(run)
	return _c
}

// Hijack provides a mock function for the type ResponseWriterHijacker
func (_mock *ResponseWriterHijacker) Hijack() (net.Conn, *bufio.ReadWriter, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Hijack")
	}

	var r0 net.Conn
	var r1 *bufio.ReadWriter
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() (net.Conn, *bufio.ReadWriter, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() net.Conn); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() *bufio.ReadWriter); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*bufio.ReadWriter)
		}
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// ResponseWriterHijacker_Hijack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hijack'
type ResponseWriterHijacker_Hijack_Call struct {
	*mock.Call
}

// Hijack is a helper method to define mock.On call
func (_e *ResponseWriterHijacker_Expecter) Hijack() *ResponseWriterHijacker_Hijack_Call {
	return &ResponseWriterHijacker_Hijack_Call{Call: _e.mock.On("Hijack")}
}

func (_c *ResponseWriterHijacker_Hijack_Call) Run(run func()) *ResponseWriterHijacker_Hijack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ResponseWriterHijacker_Hijack_Call) Return(conn net.Conn, readWriter *bufio.ReadWriter, err error) *ResponseWriterHijacker_Hijack_Call {
	_c.Call.Return(conn, readWriter, err)
	return _c
}

func (_c *ResponseWriterHijacker_Hijack_Call) RunAndReturn(run func() (net.Conn, *bufio.ReadWriter, error)) *ResponseWriterHijacker_Hijack_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type ResponseWriterHijacker
func (_mock *ResponseWriterHijacker) Write(bytes []byte) (int, error) {
	ret := _mock.Called(bytes)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(bytes)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(bytes)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(bytes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResponseWriterHijacker_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type ResponseWriterHijacker_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - bytes []byte
func (_e *ResponseWriterHijacker_Expecter) Write(bytes interface{}) *ResponseWriterHijacker_Write_Call {
	return &ResponseWriterHijacker_Write_Call{Call: _e.mock.On("Write", bytes)}
}

func (_c *ResponseWriterHijacker_Write_Call) Run(run func(bytes []byte)) *ResponseWriterHijacker_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ResponseWriterHijacker_Write_Call) Return(n int, err error) *ResponseWriterHijacker_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *ResponseWriterHijacker_Write_Call) RunAndReturn(run func(bytes []byte) (int, error)) *ResponseWriterHijacker_Write_Call {
	_c.Call.Return(run)
	return _c
}

// WriteHeader provides a mock function for the type ResponseWriterHijacker
func (_mock *ResponseWriterHijacker) WriteHeader(statusCode int) {
	_mock.Called(statusCode)
	return
}

// ResponseWriterHijacker_WriteHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteHeader'
type ResponseWriterHijacker_WriteHeader_Call struct {
	*mock.Call
}

// WriteHeader is a helper method to define mock.On call
//   - statusCode int
func (_e *ResponseWriterHijacker_Expecter) WriteHeader(statusCode interface{}) *ResponseWriterHijacker_WriteHeader_Call {
	return &ResponseWriterHijacker_WriteHeader_Call{Call: _e.mock.On("WriteHeader", statusCode)}
}

func (_c *ResponseWriterHijacker_WriteHeader_Call) Run(run func(statusCode int)) *ResponseWriterHijacker_WriteHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ResponseWriterHijacker_WriteHeader_Call) Return() *ResponseWriterHijacker_WriteHeader_Call {
	_c.Call.Return()
	return _c
}

func (_c *ResponseWriterHijacker_WriteHeader_Call) RunAndReturn(run func(statusCode int)) *ResponseWriterHijacker_WriteHeader_Call {
	_c.Run(run)
	return _c
}
