// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/selebrow/selebrow/internal/services/session"
	"github.com/selebrow/selebrow/pkg/capabilities"
	mock "github.com/stretchr/testify/mock"
)

// NewSessionService creates a new instance of SessionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionService {
	mock := &SessionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SessionService is an autogenerated mock type for the SessionService type
type SessionService struct {
	mock.Mock
}

type SessionService_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionService) EXPECT() *SessionService_Expecter {
	return &SessionService_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function for the type SessionService
func (_mock *SessionService) CreateSession(ctx context.Context, caps capabilities.Capabilities) (*session.Session, error) {
	ret := _mock.Called(ctx, caps)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 *session.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, capabilities.Capabilities) (*session.Session, error)); ok {
		return returnFunc(ctx, caps)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, capabilities.Capabilities) *session.Session); ok {
		r0 = returnFunc(ctx, caps)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*session.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, capabilities.Capabilities) error); ok {
		r1 = returnFunc(ctx, caps)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionService_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type SessionService_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - caps capabilities.Capabilities
func (_e *SessionService_Expecter) CreateSession(ctx interface{}, caps interface{}) *SessionService_CreateSession_Call {
	return &SessionService_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, caps)}
}

func (_c *SessionService_CreateSession_Call) Run(run func(ctx context.Context, caps capabilities.Capabilities)) *SessionService_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 capabilities.Capabilities
		if args[1] != nil {
			arg1 = args[1].(capabilities.Capabilities)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionService_CreateSession_Call) Return(session1 *session.Session, err error) *SessionService_CreateSession_Call {
	_c.Call.Return(session1, err)
	return _c
}

func (_c *SessionService_CreateSession_Call) RunAndReturn(run func(ctx context.Context, caps capabilities.Capabilities) (*session.Session, error)) *SessionService_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSession provides a mock function for the type SessionService
func (_mock *SessionService) DeleteSession(sess *session.Session) {
	_mock.Called(sess)
	return
}

// SessionService_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type SessionService_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - sess *session.Session
func (_e *SessionService_Expecter) DeleteSession(sess interface{}) *SessionService_DeleteSession_Call {
	return &SessionService_DeleteSession_Call{Call: _e.mock.On("DeleteSession", sess)}
}

func (_c *SessionService_DeleteSession_Call) Run(run func(sess *session.Session)) *SessionService_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *session.Session
		if args[0] != nil {
			arg0 = args[0].(*session.Session)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SessionService_DeleteSession_Call) Return() *SessionService_DeleteSession_Call {
	_c.Call.Return()
	return _c
}

func (_c *SessionService_DeleteSession_Call) RunAndReturn(run func(sess *session.Session)) *SessionService_DeleteSession_Call {
	_c.Run(run)
	return _c
}

// FindSession provides a mock function for the type SessionService
func (_mock *SessionService) FindSession(id string) (*session.Session, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindSession")
	}

	var r0 *session.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*session.Session, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *session.Session); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*session.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionService_FindSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSession'
type SessionService_FindSession_Call struct {
	*mock.Call
}

// FindSession is a helper method to define mock.On call
//   - id string
func (_e *SessionService_Expecter) FindSession(id interface{}) *SessionService_FindSession_Call {
	return &SessionService_FindSession_Call{Call: _e.mock.On("FindSession", id)}
}

func (_c *SessionService_FindSession_Call) Run(run func(id string)) *SessionService_FindSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SessionService_FindSession_Call) Return(session1 *session.Session, err error) *SessionService_FindSession_Call {
	_c.Call.Return(session1, err)
	return _c
}

func (_c *SessionService_FindSession_Call) RunAndReturn(run func(id string) (*session.Session, error)) *SessionService_FindSession_Call {
	_c.Call.Return(run)
	return _c
}

// ListSessions provides a mock function for the type SessionService
func (_mock *SessionService) ListSessions() []*session.Session {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListSessions")
	}

	var r0 []*session.Session
	if returnFunc, ok := ret.Get(0).(func() []*session.Session); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*session.Session)
		}
	}
	return r0
}

// SessionService_ListSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSessions'
type SessionService_ListSessions_Call struct {
	*mock.Call
}

// ListSessions is a helper method to define mock.On call
func (_e *SessionService_Expecter) ListSessions() *SessionService_ListSessions_Call {
	return &SessionService_ListSessions_Call{Call: _e.mock.On("ListSessions")}
}

func (_c *SessionService_ListSessions_Call) Run(run func()) *SessionService_ListSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SessionService_ListSessions_Call) Return(sessions []*session.Session) *SessionService_ListSessions_Call {
	_c.Call.Return(sessions)
	return _c
}

func (_c *SessionService_ListSessions_Call) RunAndReturn(run func() []*session.Session) *SessionService_ListSessions_Call {
	_c.Call.Return(run)
	return _c
}
