// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ShutdownHook is an autogenerated mock type for the ShutdownHook type
type ShutdownHook struct {
	mock.Mock
}

type ShutdownHook_Expecter struct {
	mock *mock.Mock
}

func (_m *ShutdownHook) EXPECT() *ShutdownHook_Expecter {
	return &ShutdownHook_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx
func (_m *ShutdownHook) Execute(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ShutdownHook_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ShutdownHook_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ShutdownHook_Expecter) Execute(ctx interface{}) *ShutdownHook_Execute_Call {
	return &ShutdownHook_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *ShutdownHook_Execute_Call) Run(run func(ctx context.Context)) *ShutdownHook_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ShutdownHook_Execute_Call) Return(_a0 error) *ShutdownHook_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ShutdownHook_Execute_Call) RunAndReturn(run func(context.Context) error) *ShutdownHook_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewShutdownHook creates a new instance of ShutdownHook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShutdownHook(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShutdownHook {
	mock := &ShutdownHook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
