// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// WDStatusController is an autogenerated mock type for the WDStatusController type
type WDStatusController struct {
	mock.Mock
}

type WDStatusController_Expecter struct {
	mock *mock.Mock
}

func (_m *WDStatusController) EXPECT() *WDStatusController_Expecter {
	return &WDStatusController_Expecter{mock: &_m.Mock}
}

// Status provides a mock function with given fields: c
func (_m *WDStatusController) Status(c echo.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WDStatusController_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type WDStatusController_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - c echo.Context
func (_e *WDStatusController_Expecter) Status(c interface{}) *WDStatusController_Status_Call {
	return &WDStatusController_Status_Call{Call: _e.mock.On("Status", c)}
}

func (_c *WDStatusController_Status_Call) Run(run func(c echo.Context)) *WDStatusController_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *WDStatusController_Status_Call) Return(_a0 error) *WDStatusController_Status_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WDStatusController_Status_Call) RunAndReturn(run func(echo.Context) error) *WDStatusController_Status_Call {
	_c.Call.Return(run)
	return _c
}

// NewWDStatusController creates a new instance of WDStatusController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWDStatusController(t interface {
	mock.TestingT
	Cleanup(func())
}) *WDStatusController {
	mock := &WDStatusController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
