{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "selebrow.fullname" . }}
  namespace: {{ .Values.selebrow.namespace | default .Release.Namespace }}
  labels:
    {{- include "selebrow.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - get
      - list
      - watch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "selebrow.fullname" . }}
  namespace: {{ .Values.selebrow.namespace | default .Release.Namespace }}
  labels:
    {{- include "selebrow.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "selebrow.fullname" . }}
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "selebrow.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}